### ISSUE TITLE
Needs a 1.12 Update

### ISSUE THREAD

**Issue by Blaxe97** [rymate1234/Overviewer-GUI#6]
a day ago, an issue was solved in the minecraft overviewer github, related with the new bed textures, an update for this gui is needed so it can use de newer version... i guess

**Comment by rymate1234** [comment]
You'll probably have to wait for the windows builds this application automatically downloads to support 1.12

**Comment by CounterPillow** [comment]
the problem is that the automatic windows builders for overviewer are down, and have been for months

**Comment by Blaxe97** [comment]
is there a way to manually build it (i'm no coding expert)

**Comment by Blaxe97** [comment]
well, the waiting is eternal, i guess i can think this program is dead by now...right?

**Comment by rymate1234** [comment]
Update: The latest version of the Overviewer for windows is now live on http://overviewer.org/downloads however I need to update the GUI to support how it's extracted

**Comment by rymate1234** [comment]
The 1.3.1 release should fix this, check it out!
